apiVersion: v1
kind: Service
metadata:
  name: helloworld-service-nodeport
spec:
  ports:
  - port: 31001
    nodePort: 31001
    targetPort: nginxport
    protocol: TCP
  selector:
    app: helloworld
  type: NodePort
