apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db-only
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: db-only
    spec:
      containers:
      - name: db
        image: mysql:5.7
        ports:
        - name: mysql-port
          containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: password
---
apiVersion: v1
kind: Service
metadata:
  name: wp-db-service
spec:
  ports:
  - port: 3306
    targetPort: mysql-port
    protocol: TCP
  selector:
    app: db-only
  type: NodePort
